<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>QuanLySinhVien</RootNamespace>
    <AssemblyName>QuanLySinhVien</AssemblyName>
    <!-- Cho phép chạy trên .NET mới hơn nếu máy chưa cài .NET 8 runtime -->
    <RollForward>Major</RollForward>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <ApplicationDefaultFont>Segoe UI, 9pt</ApplicationDefaultFont>
  </PropertyGroup>

</Project>
